name: Latest blog post workflow

on:
  schedule:
    - cron: "*/1 * * * *" # every 1 minute (testing mode)
  workflow_dispatch: # allows you to run manually from Actions tab

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@kaushikblogs"
