name: Update latest Medium posts

on:
  schedule:
    - cron: '0 0 */7 * *' # Runs every 7 days at midnight UTC
  workflow_dispatch: # Allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update README with latest blog posts
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@kaushikblogs"
